# Generated by Django 4.1.5 on 2023-01-24 20:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListProducts',
            fields=[
                ('_id_list', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=200)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('client', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
