# Generated by Django 4.1.5 on 2023-01-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listproducts',
            old_name='date_created',
            new_name='creation_date',
        ),
    ]
