# Generated by Django 4.1.5 on 2023-01-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_rename_date_created_listproducts_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listproducts',
            name='type',
            field=models.CharField(default='O', max_length=100, verbose_name=(('V', 'verdura'), ('L', 'Lacteo'), ('F', 'Fruta'), ('CR', 'Cereal'), ('C', 'Carnes'), ('O', 'otros'))),
        ),
    ]
