# Generated by Django 4.1.5 on 2023-01-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_listproducts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproducts',
            name='type',
            field=models.CharField(blank=True, choices=[('V', 'verdura'), ('L', 'Lacteo'), ('F', 'Fruta'), ('CR', 'Cereal'), ('C', 'Carnes'), ('O', 'otros')], default='O', help_text='tipo producto', max_length=100),
        ),
    ]
