# Generated by Django 4.1.5 on 2023-01-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_alter_listproducts_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listproducts',
            name='status_delete',
            field=models.BooleanField(default=False),
        ),
    ]
