# Generated by Django 4.1.5 on 2023-01-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0007_alter_listproducts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproducts',
            name='type',
            field=models.CharField(blank=True, choices=[('Verdura', 'Verdura'), ('Lacteo', 'Lacteo'), ('Fruta', 'Fruta'), ('Cereal', 'Cereal'), ('Carnes', 'Carnes'), ('Otro', 'Otro')], default='Otro', help_text='tipo producto', max_length=100),
        ),
    ]
