# Generated by Django 4.1.5 on 2023-01-30 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0008_alter_listproducts_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listproducts',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='listproducts',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listproducts',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
